### ISSUE TITLE
volo

### ISSUE THREAD

**Issue by FabioZTessitore** [Billie99/Python#1]
La conversione galloni-litri non è necessaria

Il test sui dati in ingresso non va bene

I nomi delle variabili, usa qualcosa di più comprensibile

**Comment by Billie99** [comment]
Va bene! Le operazioni che ho fatto sul tempo sono corrette o devo modificarle?

**Comment by FabioZTessitore** [comment]
A occhio sembrano buone ma non ho testato

Il 4 feb 2017 8:11 PM, "Billie99" <notifications@github.com> ha scritto:

**Comment by Billie99** [comment]
Devo eliminare la riga sulla conversione galloni-litri?

**Comment by FabioZTessitore** [comment]
Si, non è richiesta

Il 4 feb 2017 8:16 PM, "Billie99" <notifications@github.com> ha scritto:

**Comment by Billie99** [comment]
Va bene

**Comment by FabioZTessitore** [comment]
aggiustiamo?

**Comment by Billie99** [comment]
Prof il nome delle variabili l'ho modificato! le operazioni sul tempo non stanno fatte bene?

**Comment by FabioZTessitore** [comment]
va bene, ma hai caricato ora la versione buona
